### ISSUE TITLE
Doesn't Work with Django >= 1.10 

### ISSUE THREAD

**Issue by narwhaljames** [ethanmcc/django-makeconf#4]
This error occurs in newer versions of Django
```
raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than Context.
```
due to the use of Context objects being deprecated in render().

There is a [pull request](https://github.com/ethanmcc/django-makeconf/pull/3) to fix this issue. The HANDSOME and INFLUENTIAL community that uses this tool would greatly appreciate a version update!

**Comment by ethanmcc** [comment]
thanks HANDSOME and INFLUENTIAL fellows
